#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- CMS database and user
    CREATE USER ${CMS_DATABASE_USERNAME} WITH PASSWORD '${CMS_DATABASE_PASSWORD}';
    CREATE DATABASE ${CMS_DATABASE_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${CMS_DATABASE_NAME} TO ${CMS_DATABASE_USERNAME};
    \c ${CMS_DATABASE_NAME}
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${CMS_DATABASE_USERNAME};
    CREATE SCHEMA IF NOT EXISTS ${CMS_DATABASE_SCHEMA} AUTHORIZATION ${CMS_DATABASE_USERNAME};
    
    -- Superset database and user
    CREATE USER ${SUPERSET_DB_USER} WITH PASSWORD '${SUPERSET_DB_PASSWORD}';
    CREATE DATABASE ${SUPERSET_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${SUPERSET_DB_NAME} TO ${SUPERSET_DB_USER};
    \c ${SUPERSET_DB_NAME}
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${SUPERSET_DB_USER};
    CREATE SCHEMA IF NOT EXISTS ${SUPERSET_DB_SCHEMA} AUTHORIZATION ${SUPERSET_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${SUPERSET_DB_SCHEMA} GRANT ALL ON TABLES TO ${SUPERSET_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${SUPERSET_DB_SCHEMA} GRANT ALL ON SEQUENCES TO ${SUPERSET_DB_USER};

    -- OLAP Sandbox Database
    CREATE USER ${OLAP_SANDBOX_DB_USER} WITH PASSWORD '${OLAP_SANDBOX_DB_PASSWORD}';
    CREATE DATABASE ${OLAP_SANDBOX_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${OLAP_SANDBOX_DB_NAME} TO ${OLAP_SANDBOX_DB_USER};
    \c ${OLAP_SANDBOX_DB_NAME}
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${OLAP_SANDBOX_DB_USER};
EOSQL