#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- CMS database and user
    CREATE USER ${CMS_DATABASE_USERNAME} WITH PASSWORD '${CMS_DATABASE_PASSWORD}';
    CREATE DATABASE ${CMS_DATABASE_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${CMS_DATABASE_NAME} TO ${CMS_DATABASE_USERNAME};
    \c ${CMS_DATABASE_NAME}
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${CMS_DATABASE_USERNAME};
    
    -- Superset database and user
    CREATE USER ${SUPERSET_DB_USER} WITH PASSWORD '${SUPERSET_DB_PASSWORD}';
    CREATE DATABASE ${SUPERSET_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${SUPERSET_DB_NAME} TO ${SUPERSET_DB_USER};
    \c ${SUPERSET_DB_NAME}
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${SUPERSET_DB_USER};
EOSQL