services:
  dev:
    build: .
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: postgres:18
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SUPERSET_DB_NAME=$SUPERSET_DB_NAME
      - SUPERSET_DB_USER=$SUPERSET_DB_USER
      - SUPERSET_DB_PASSWORD=$SUPERSET_DB_PASSWORD
      - CMS_DATABASE_NAME=$CMS_DATABASE_NAME
      - CMS_DATABASE_USERNAME=$CMS_DATABASE_USERNAME
      - CMS_DATABASE_PASSWORD=$CMS_DATABASE_PASSWORD
      - OLAP_SANDBOX_DB_NAME=$OLAP_SANDBOX_DB_NAME
      - OLAP_SANDBOX_DB_USER=$OLAP_SANDBOX_DB_USER
      - OLAP_SANDBOX_DB_PASSWORD=$OLAP_SANDBOX_DB_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh

  cms:
    build:
      context: ../apps/cms-payload
      dockerfile: Dockerfile.dev
    volumes:
      - ../apps/cms-payload:/app
      # Protection des répertoires internes
      - /app/node_modules
      - /app/.next
    tty: true
    stdin_open: true
    env_file:
      - .env
    environment:
      - PATH=$PATH:/app/node_modules/.bin
      - DATABASE_URL=postgres://$CMS_DATABASE_USERNAME:$CMS_DATABASE_PASSWORD@database:5432/$CMS_DATABASE_NAME
      - PAYLOAD_SECRET=$CMS_PAYLOAD_SECRET
      - NEXT_PUBLIC_SERVER_URL=$CMS_NEXT_PUBLIC_SERVER_URL
      - PAYLOAD_DB_PUSH=$CMS_PAYLOAD_DB_PUSH

  valkey:
    image: valkey/valkey:8-alpine
    restart: always

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SUPERSET_SECRET_KEY=$SUPERSET_SECRET_KEY
      - SUPERSET_REDIS_HOST=valkey
      - SUPERSET_REDIS_PORT=6379
      - SUPERSET_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://$SUPERSET_DB_USER:$SUPERSET_DB_PASSWORD@database:5432/$SUPERSET_DB_NAME?options=-csearch_path%3D$SUPERSET_DB_SCHEMA
      # Embedding
      - SUPERSET_ENABLE_CORS=true
      - SUPERSET_FEATURE_EMBEDDED_SUPERSET=$SUPERSET_FEATURE_EMBEDDED_SUPERSET
      - SUPERSET_CONFIG_PATH=/app/superset_config.py
    volumes:
      - superset-data:/app/superset_home
      - ./superset/superset_config.py:/app/superset_config.py
    depends_on:
      - database
      - valkey

volumes:
  postgres-data:
  superset-data:
